display_data/urls.py
from django.urls import path

from . import views

app_name = 'display_data'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_page, name='login'),
    path('login_token', views.login_token_page, name='login_token'),
    path('receiver', views.do_openid_receive, name='openid_receive'),
    path('CIDForm', views.get_component_ID, name='component ID form'),
    path('FetchInst', views.fetch_institutions, name='fetch insts'),
    path('listInst', views.list_institutions, name='list insts'),
    path('inst/<str:inst_code>', views.view_institution, name='view inst'),
    path('inst/<str:inst_code>/<str:ct_code>',
         views.view_institution_comp_type, name='view inst comp_type'),
    path('complist',
         views.view_comp_table, name='view comp list'),
    path('summary', views.cached_summary, name='summary of cached'),
    path('tests/<str:component_id_or_sn>', views.test_summary, name='test results'),
    path('test_detail/<str:component_id_or_sn>/<int:count>/', views.tests_details, name='detail'),
    path('upload', views.upload_test, name='upload form'),
    path('upload_successful', views.upload_successful, name='upload successful'),
    path('test_plotting', views.plotting_example, name='test plotting'),
    path('another_request/<str:serial>/', views.request_component_tests, name='another request'),
    path('component/<str:serial>', views.get_component_view, name='view component'),
    path('defect_tree_view/<str:component_id>', views.defect_tree_view, name='defect_tree_view'),
    path(
        'module_summary_test/<str:component_id>', views.module_summary_test_view,
        name="module_summary_test_view"
    ),
    path(
        'module_summary_test/<str:component_id>/download', views.module_summary_test_json_view,
        name="module_summary_test_json_view"
    ),
    path(
        'hybrid_summary_test/<str:component_id>', views.hybrid_summary_test_view,
        name="hybrid_summary_test_view"
    ),
]

# path function has two required arguments: route and view
# route: string that contains a URL pattern
# view: to call the specific view function
# kwargs: arbitrary keyword arguments can be passed in a directory to the target view
# name: name of the URL

djangoWebGUI/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('display_data.urls')),
    path('admin/', admin.site.urls),
]

display_data/forms.py
from django import forms
from django.forms.widgets import CheckboxInput

class ComponentIDForm(forms.Form):
    without_request = forms.BooleanField(label='check local database first', widget=CheckboxInput, required=False)
    Component_ID = forms.CharField(label='ATLAS serial number or component ID', max_length=100, required=True)

class AccessForm(forms.Form):
    key1 = forms.CharField(label='access key 1', widget=forms.PasswordInput)
    key2 = forms.CharField(label='access key 2', widget=forms.PasswordInput)

    # Optionally allow redirect to previous page
    redirect = forms.CharField(max_length = 100, required = False,
                               widget=forms.HiddenInput)

class TokenForm(forms.Form):
    db_token = forms.CharField(max_length = 2000)

class Upload_Test(forms.Form):
    Component_ID = forms.CharField(label='component ID', max_length=100)
    comments = forms.CharField(label='comments', max_length=300)
    institution = forms.CharField(label='institution', max_length=100)
    file = forms.FileField(label='.JSON file')

class ListFilterForm(forms.Form):
    """
    Form to store/update data on filter for listComponents.

    The current filter information is hidden, and new items can be added.
    """

    def __init__(self, *args, choices=None, **kwargs):
        super(ListFilterForm, self).__init__(*args, **kwargs)

        if choices:
            if "comp_pick" in choices:
                self.fields["comp_pick"].choices = choices["comp_pick"]

    comp_pick = forms.ChoiceField(label="Select component type", widget=forms.Select, required = False)

class OpenidForm(forms.Form):
    access_token = forms.CharField(max_length = 1000)
    session_expires_in = forms.DecimalField(max_digits = 6)
    id_token = forms.CharField(max_length = 2000)
    session_state = forms.CharField(max_length = 128)
    token_type = forms.CharField(max_length = 10)
    expires_in = forms.DecimalField(max_digits = 6)

display_data/views.py
"""

Views module for ITK web app
"""

import datetime
import logging
import pprint
import re
import sys
import time
import urllib

import display_data.do_stuff
import display_data.hybrid_summary_test as hybrid_summary_test
import display_data.module_summary_test as module_summary_test
import django.template.defaulttags
import django.urls
import django.utils.html
import django.http
import numpy as np
from display_data.bad_channel_tracing import Defect_Mapping
from display_data.dbAccess import _SITE_URL
from display_data.do_plotting_stuff import get_plot
from display_data.do_stuff import (get_associated_tests,
                                   list_components,
                                   list_institute_components, list_institutes,
                                   store_component_from_db_in_model,
                                   upload_test_result)
from display_data.models import ComponentInfo, Institute, TestSummary
from display_data.plotting import (atlas18_cv_test, atlas18_shape_metrology,
                                   full_strip_test, manufactering_data_atlas18,
                                   response_curve, strobe_delay,
                                   three_point_gain)
from display_data.specific_stuff import interesting_ct_codes
from display_data import pager
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.decorators.http import (require_http_methods, require_GET,
                                          require_POST)

from . import app_settings
from .forms import AccessForm, ComponentIDForm, ListFilterForm, OpenidForm, TokenForm, Upload_Test
from display_data import models as web_app_models

logger = logging.getLogger(__name__)

id_re = re.compile("[\da-f]{32}$", re.IGNORECASE)
# Match only Strips components
sn_re = re.compile("20US[A-Z]{2}[\dA-Z][\d]{7}$")

def comp_valid(some_id):
    if id_re.match(some_id):
        return True
    if sn_re.match(some_id):
        return True
    return False

@require_GET
def index(request):
    """
    Main home page
    """

    ctxt = {'example_list': [
        {"id": "20USGAM1002094", "desc": "An AMAC"},
        {"id": "20USGAH1003118", "desc": "An HCC"},
        {"id": "20USGWA1222000", "desc": "An ABC"},
        {"id": "20USBML1234841", "desc": "An LS Module"},
        {"id": "20USBHX2001244", "desc": "An X hybrid"},
        {"id": "20USBLC2000007", "desc": "An LS Stave"},
        {"id": "20USELC1000031", "desc": "A Petal"},
      ]}

    return render(request, 'index.html', ctxt)


@require_GET
def upload_successful(request):
    return render(request, 'upload_successful.html')


@require_GET
def plotting_example(request):
    x = [1, 2, 3, 4]
    y = [1, 2, 3, 4]
    plot = get_plot(x, y)
    context = {}
    context['plot'] = plot
    return render(request, 'plotting_test.html', context)


def do_auth(request, key1, key2):
    if len(key1) == 0 or len(key2) == 0:
        # Empty, don't try connecting
        messages.add_message(request, messages.WARNING,
                             'Authentication failed')
        return None

    # If we're given keys, use them to get token even if we have one already
    failed, token = display_data.do_stuff.access(key1, key2)
    if failed is True:
        logger.error("Authentication failed")
        messages.add_message(request, messages.WARNING,
                             'Authentication failed')

        try:
            del request.session["session_db_token"]
        except KeyError:
            pass
        try:
            del request.session["session_db_expires_at"]
        except KeyError:
            pass

        return None
    request.session["session_db_token"] = token
    now = time.time()
    # Valid for 30 mins
    request.session["session_db_expires_at"] = int(now + 25 * 60)

    return token

class NoTokenException(Exception):
    pass

def check_auth(request):
    try:
        s_expires = request.session["session_db_expires_at"]
        if time.time() > int(s_expires):
            logger.error("Authentication expired (%s vs %s)" %
                             (time.time(), s_expires))
            messages.add_message(request, messages.WARNING,
                                 'Authentication expired')
            raise NoTokenException()

        token = request.session["session_db_token"]
    except KeyError:
        logger.error("Authentication needed")
        messages.add_message(request, messages.WARNING,
                             'No authentication provided')
        raise NoTokenException()

    return token


def have_auth(request):
    have_auth = False
    try:
        request.session["session_db_token"]
        s_expires = request.session["session_db_expires_at"]
        if time.time() < int(s_expires):
            have_auth = True
    except KeyError:
        pass

    return have_auth

def wrap_auth(func):
    """
    Decorator to redirect to login page on failed auth.

    Note that we don't call check_auth here as it might not be needed.
    """

    def wrapped(request, *args, **kwargs):
        try:
            return func(request, *args, **kwargs)
        except NoTokenException:
            return HttpResponseRedirect(django.urls.reverse('display_data:login') + "?" + urllib.parse.urlencode({"redirect": request.get_full_path_info()}))

    return wrapped


@require_GET
def do_openid_receive(request):
    # Receive the token from remote server
    form = OpenidForm(request.GET)

    if not form.is_valid():
        logger.info("Open ID form results is not valid")

        messages.add_message(
            request, messages.WARNING, 'Login failed')

        return HttpResponseRedirect('/')

    new_token = form.cleaned_data.get('id_token')
    exp = int(form.cleaned_data.get('expires_in'))

    request.session["session_db_token"] = new_token
    now = time.time()
    request.session["session_db_expires_at"] = int(now + exp)

    return HttpResponseRedirect('/')

@require_http_methods(["GET", "POST"])
def login_page(request):
    logger.debug("Login page method %s" % request.method)

    # This should report the full host name
    server_host = request.get_host()

    # If we're running on dev (locally), open id just works
    allow_using_openid = "localhost" in server_host
    if app_settings.OPENID_CLIENT_ID:
        allow_using_openid = True

    if request.method == 'GET':
        destination = request.GET.get("redirect", default = "/")
        if have_auth(request):
            messages.add_message(
                request, messages.WARNING, 'Already logged in')
            return HttpResponseRedirect(destination)

        form = AccessForm(initial = {"redirect": destination})

        context = {
            'form': form,
        }

        context["do_openid"] = allow_using_openid
        if allow_using_openid:
            context["client_id"] = app_settings.OPENID_CLIENT_ID
            if app_settings.OPENID_CLIENT_SECRET:
                # On localhost, we don't need secret
                context["client_secret"] = app_settings.OPENID_CLIENT_SECRET
            # Name that gets redirected to do_openid_receive
            context['receiver'] = 'receiver'
            context["scope"] = "openid https://itkpd-test.unicorncollege.cz"
            context["base_oidc"] = "https://uuidentity.plus4u.net/uu-oidc-maing02/bb977a99f4cc4c37a2afce3fd599d0a7/oidc/auth?acrValues=standard high veryHigh"

        return render(request, 'login.html', context)

    # Get form data from the request
    form = AccessForm(request.POST)
    if not form.is_valid():
        messages.add_message(request, messages.WARNING, 'Invalid form data')
        return HttpResponseRedirect('/')

    key1, key2 = form.cleaned_data.get('key1'), form.cleaned_data.get('key2')
    token = do_auth(request, key1, key2)

    if token is not None:
        messages.add_message(request, messages.WARNING, 'Login successful')

    destination = form.cleaned_data.get('redirect', '/')

    return HttpResponseRedirect(destination)

@require_http_methods(["GET", "POST"])
def login_token_page(request):
    logger.debug("Login via token method: %s" % request.method)

    if request.method == 'GET':
        if have_auth(request):
            messages.add_message(
                request, messages.WARNING, 'Already logged in')
            return HttpResponseRedirect('/')

        form = TokenForm()

        return render(request, 'login_token.html',
                      {'form': form})


    # Get form data from the request
    form = TokenForm(request.POST)
    if not form.is_valid():
        messages.add_message(request, messages.WARNING, 'Invalid form data')
        return HttpResponseRedirect('/')

    new_token = form.cleaned_data.get('db_token')

    if new_token is not None:
        messages.add_message(request, messages.WARNING, 'Login successful')
    else:
        messages.add_message(request, messages.WARNING, 'Login not successful')
        return HttpResponseRedirect('/')

    # Should do some validation
    request.session["session_db_token"] = new_token
    # Valid for 30 mins
    now = time.time()
    request.session["session_db_expires_at"] = int(now + 25 * 60)

    return HttpResponseRedirect('/')

@require_http_methods(["GET", "POST"])
@wrap_auth
def upload_test(request):
    if request.method == 'POST':
        form = Upload_Test(request.POST, request.FILES)
        if form.is_valid():
            component_ID = form.cleaned_data.get('Component_ID')
            if id_re.match(form.cleaned_data.get('Component_ID')):
                messages.add_message(request, messages.WARNING, 'Bad component ID (expecting 32 hexdigit code)')
                return HttpResponseRedirect('upload')
            comments = form.cleaned_data.get('comments')
            institution = form.cleaned_data.get('institution')
            # do things
            token = check_auth(request)

            try:

display_data/templates/ComponentID.html
{% extends "base.html" %}

{% load static %}

{% block page_title %}Request component status{% endblock %}
{% block title %}Get component status summary{% endblock %}

{% block javascript %}
<script src="{% static 'main.js' %}" defer> </script>
{% endblock %}

{% block content %}
<form action="{% url 'display_data:component ID form' %}" method="post" id="form">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="get_test_summary" value="Get test summary">
  <input type="submit" name="get_tree_view" value="Get defect tree view">
  <input type="submit" name="get_module_summary_test" value="Get module summary test view">
  <input type="submit" name="get_hybrid_summary_test" value="Get hybrid summary test view">
</form>
{% endblock %}

{% block loader %}
<div id="loader_box">
  <div class="loader-wrapper">
    <span class="loader"><span class="loader-inner"></span></span>
  </div>
</div>
{% endblock %}

display_data/templates/base.html
<html>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
<!-- and it's easy to individually load additional languages -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/json.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/python.min.js"></script>
<script>hljs.highlightAll();</script>

<head>
<title>ITk Module Test GUI - {% block page_title %}Top{% endblock page_title %}</title>
</head>

<body>
{% block javascript %}{% endblock %}

<h1 style="background-color: rgb(56, 125, 187); color: white; text-indent: 10px;">ITk Strips Test GUI</h1>

<img src="{% static 'images/atlas_logo.png' %}" alt="atlas_logo" width="164.25" height="73.5" align="right">
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="{% url 'display_data:index' %}">Home</a></li>
            <li><a href="{% url 'display_data:component ID form' %}">Get component status summary</a></li>
            <!-- <li><a href="{% url 'display_data:upload form' %}">Upload test</a></li> -->
            <li><a href="{% url 'display_data:summary of cached' %}">Recently retrieved component summaries</a></li>
            <li><a href="{% url 'display_data:list insts' %}">List of institutes</a></li>
            <li><a href="{% url 'display_data:view comp list' %}">List of components</a></li>
            <li><a href="{% url 'display_data:login' %}"}>Log in page for token</a></li>
        </ul>
        {% endblock %}
    </div>

<h2 style="text-indent: 10px">{% block title %}Home{% endblock title %}</h2>
<hr>
    <div id="messages">
        {% block messages %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    {% block loader %}
      {# Somewhere to put spinner code while loading #}
    {% endblock loader %}
</body>
</html>

display_data/templates/comp_list_table.html
{% extends "base.html" %}

{% block page_title %} Component list {% endblock %}
{% block title %} List of components {% endblock %}

{% block content %}

<form action="" method="get" id="filter_form">
  {% csrf_token %}
  {{ filter_form }}
  <input type="submit" value="Update filter">
  <input type="hidden" name="page" value="{{page_obj.number}}">
</form>

<p> List of components </p>

<table>
  <thead>
    <tr>
      {% for name in col_list %}
      <th>{{name}}</th>
      {% endfor %}
      <th><!-- details button --></th>
      <th><!-- DB link --></th>
    </tr>
  </thead>
  <tbody>
    {% for comp in comp_list %}
    <tr>
      {% for data in comp.table_data %}
      <td>{{ data }}</td>
      {% endfor %}
      <td>
        <a href="{% url 'display_data:view component' comp.code %}">Details</a>
      </td>
      <td>
        <a href="https://itkpd-test.unicorncollege.cz/componentView?code={{ comp.code}}" target="_blank" rel="noopener noreferrer">DB Link</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<p> Finished list of components </p>

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

display_data/templates/component.html
{% extends "base.html" %}

{% load static %}

{% block page_title %} Component info for {{ component.serialNumber }} {% endblock %}
{% block title %} Component summary for {{ component.serialNumber }} {% endblock %}

{% block javascript %}
<script src="{% static 'main.js' %}" defer> </script>
{% endblock %}

{% block content %}

<p style="margin-bottom:0.2cm">ATLAS serial number: {{ component.serialNumber }} <br> </p>
<p style="margin-bottom:0.5cm">Component ID: {{ component.component_ID }} </p>
<p style="margin-bottom:0.2cm">Parent component: {{ component.parents_type }} <br> </p>
{% if component.parents_type != 'No parent components' %}
<p style="margin-bottom:0.2cm">ATLAS serial number: <a href="{% url 'display_data:view component' component.parents_serial %}">{{ component.parents_serial }}</a> (click on link for new request) <br> </p>
<p style="margin-bottom:1cm">Component ID: {{ component.parents_ID }} </p>
{% endif %}

<a href="{% url 'display_data:another request' component.component_ID %}">Fetch test summary</a> </p>

<a href="{% url 'display_data:defect_tree_view' component.component_ID %}">Fetch defect tree</a> </p>

{% if link_summary %}
<p>Generate component specific summary test: <a href="{{ link_summary }}"> here </a> </p>
{% endif %}

<a href="https://itkpd-test.unicorncollege.cz/componentView?code={{ component.component_ID}}" target="_blank" rel="noopener noreferrer">Link to DB</a>


</div>
{% endblock %}

display_data/templates/hybrid_summary_test.html
{% extends "base.html" %}

{% block page_title %} Hybrid summary test {% endblock %}
{% block title %} Hybrid summary test {% endblock %}

{% block content %}



<p>
    Hybrid summary test for ATLAS ITK project
</p>

<p>
    <a href="{{test_summary_link}}">Link to generic test summary </a>
</p>

<ul>
    <li>Time start is {{ time_start }}</li>
    <li>Time end is {{ time_end }}</li>
    <li>Runtime is {{ runtime }}</li>
</ul>

<p>
    This component was looked up by the key "{{lookup_key}}".
</p>
<p>
    <a href="{{component_db_link}}">DB link to component</a>
</p>
<p>
    Hybrid summary test as dict is:
</p>
<p>
    <pre><code class="language-python">{{hybrid_summary_string}}</code></pre>
</p>

{% endblock %}

display_data/templates/inst_comp_list.html
{% extends "base.html" %}

{% block page_title %} List {{ inst_code }} {{ ct_code }} {% endblock %}
{% block title %} List of components at institute {% endblock %}

{% block content %}

<p> Institute {{ inst_code }} component type {{ ct_code }}
<p> NB only the top 10 components are listed

    {% for comp in have_list %}
      <p>Test summary for 
        {% if comp.sn %}
          <a href="{% url 'display_data:test results' comp.sn %}">
            {{ comp.sn }}
          </a>
        {% else %}
          <a href="{% url 'display_data:test results' comp.code %}">
            anonymous
          </a>
        {% endif %}
    {% endfor %}

    {% for comp in missing_list %}
    <form style="margin: 0; padding: 0;" action="{% url 'display_data:component ID form' %}" method="POST">
        {% if comp.sn %}
        <p> Component {{ comp.sn }}
        {% elif comp.alt_id %}
        <p> Alt component {{ comp.alt_id }}
        {% else %}
        <p> Anonymous component {{ comp.code }}
        {% endif %}
      {% csrf_token %}
        <input hidden="true" type="checkbox" name="without_request" id="id_without_request">
        <input hidden="true" name="Component_ID" id="id_Component_ID" value="{{comp.code}}">
        <input type="submit" value="Fetch">
    </form>
 </p>
    {% endfor %}

{% endblock %}

display_data/templates/login_token.html
{% extends "base.html" %}
{% load static %}

{% block page_title %} Login {% endblock %}
{% block title %} Login to Production Database using token {% endblock %}

{% block javascript %}
<script src="{% static 'main.js' %}" defer> </script>
{% endblock %}

{% block content %}

<form action="{% url 'display_data:login_token' %}" method="post" id="form">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Get">
</form>
{% endblock %}

display_data/templates/module_summary_test.html
{% extends "base.html" %}

{% block page_title %} Module summary test {% endblock %}
{% block title %} Module summary test {% endblock %}

{% block content %}

<p>
    Hey here's some content
</p>

<ul>
    <li>Time start is {{ time_start }}</li>
    <li>Time end is {{ time_end }}</li>
    <li>Runtime is {{ runtime }}</li>
</ul>

<p>
    This module, looked up by the key "{{lookup_key}}" is of type {{component_api_response.type.name}} and is at {{component_api_response.currentLocation.name}} as of the date {{component_api_response.currentLocationTs}}.
</p>
<p>
    Serial number is {{component_api_response.serialNumber}}, and component ID/code is {{module_summary_test_result.component}}.
</p>

<p>
    <a href="{{component_db_link}}">DB link to component </a>
</p>
<p>
    <a href="{{test_summary_link}}">Link to generic test summary </a>
</p>
<p>
    <a href="{{json_download_link}}">Download link for JSON</a>
</p>

<p>
    This module summary test has was produced by module test function version {{module_summary_test_result.properties.module_test_func_version}} with git hash {{module_summary_test_result.properties.module_test_git_hash}}
</p>
{% if module_summary_test_result.comments %}
<p>
    Module comments are: 
    <ul>
        {% for comment in module_summary_test_result.comments %}
        <li>
            "{{comment}}"
        </li>
        {% endfor %}
    </ul>
</p>
{% endif %}
<p>
    Module summary test checks:
</p>
<ul>
    <li>
        Module finished assembly: {{module_summary_test_result.results.module_finished_assembly}}
    </li>
    <li>
        All required sub components are present: {{module_summary_test_result.results.all_required_subcomponents_present}}. 
        {% if not module_summary_test_result.results.all_required_subcomponents_present %}
        <dl>
            {% for subcomponent_name, present in module_summary_test_result.results.required_subcomponents_present.items %}
                <dt>{{subcomponent_name}} present - </dt> <dd>{{present}}</dd>
            {% endfor %}
        </dl>
        {% endif %}
    </li>
    <li>
        All required tests done: {{module_summary_test_result.results.all_required_tests_done}}
        {% if not module_summary_test_result.results.all_required_tests_done %}
        <dl>
            {% for test_name in missing_tests %}
                <dt>{{test_name}} performed - </dt> <dd>Not done</dd>
            {% endfor %}
        </dl>
        {% endif %}
    </li>
    <li>
        <p>
            The most recent run of each required test passed: {{module_summary_test_result.results.all_recent_required_tests_passed}}
        </p>
        {% if not module_summary_test_result.results.all_recent_required_tests_passed %}
        <p>
            Failing tests:
        </p>
        <dl>
            {% for test_name, payload in module_summary_test_result.results.per_test_check.items %}
                {% if payload.0 %}
                    <!-- If test passed, don't do anything -->
                {% else %}
                    <dt>{{test_name}}</dt>
                    {% if payload.1 is not None %}
                        <dd>failed with comments:
                            <ul>
                                {% for comment_dict in payload.1 %}
                                    <li>
                                        "{{comment_dict.comment}}"
                                    </li>
                                {% endfor %}
                            </ul>
                            <a href="{{ test_id_to_url_dict|get_item:payload.2 }}">DB link to test run </a>
                            {{payload.2}}
                        </dd>
                    {% else %}
                        <dd>
                            Failed with no comment.
                            <a href="{{ test_id_to_url_dict|get_item:payload.2 }}">DB link to test run </a>
                            {{payload.2}}
                        </dd>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </dl>
        {% endif %}
    </li>
</ul>


{% if show_debug %}
    <p>For debug reasons, the module summary test dict and some other information appear below</p>
    <p>Module summary test dict:</p>

    <pre>
        {{module_summary_test_result | pprint}}
    </pre>
    <p>Component API response</p>
    <pre>{{component_api_response | pprint}}</pre>
{% endif %}

{% endblock %}

display_data/templates/plotting_test.html
{% extends "base.html" %}

{% block page_title %} PLOTTING {% endblock %}
{% block title %} Plotting test {% endblock %}

{% block content %}
    {% if plot %}
        <img src="data:image/png;base64, {{ plot|safe }}" width="600">
    {% endif %}
{% endblock content %}

display_data/templates/simple_form.html
{% for field in form %}
  {{ field.errors }}
  {{ field.label_tag }} {{ field }}
{% endfor %}

display_data/templates/summary.html
{% extends "base.html" %}

{% block page_title %} Known report {% endblock %}
{% block title %} Local test info {% endblock %}

{% block content %}

{% for test in test_comps %}
<p>Test summary for component
  <a href="{% url 'display_data:test results' test.id %}">{% if test.name %} {{ test.name }} on {% endif %} {{ test.sn }}</a> </p>
{% endfor %}

{% endblock %}

display_data/templates/upload_successful.html
{% extends "base.html" %}

{% block page_title %} Upload {% endblock %}
{% block title %} Upload test complete {% endblock %}

{% block content %}
<p>Upload successful!</p>
{% endblock %}

display_data/templates/upload_test_form.html
{% extends "base.html" %}

{% block page_title %} UPLOAD {% endblock %}
{% block title %} Upload test {% endblock %}

{% block content %}
<p style="margin-bottom:1cm;">The content of the institution field has to match your specific institution
  code, i.e. HUBERLIN. Check ITk production database if unsure.</p>
<form action="{% url 'display_data:upload form' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Upload">
</form>
{% endblock %}

display_data/templates/view_inst.html
{% extends "base.html" %}

{% block page_title %} Inst {{ inst.inst_code }}{% endblock %}
{% block title %}Page for institute {{ inst.inst_code }}{% endblock %}

{% block content %}
    <p>Summary of institute {{ inst.inst_code }} <p>

      {% for ct in comp_types %}
        <p>
          <li><a href="{% url 'display_data:view inst comp_type' inst.inst_code ct %}">
          {{ ct }}</a></li>
        </p>
      {% endfor %}
{% endblock %}